name: Trigger auto deployment for card-game-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/card-game-api-AutoDeployTrigger-6ef7747e-db35-487a-874d-d2d907a184af.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CARDGAMEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARDGAMEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARDGAMEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: backend/Dockerfile
          registryUrl: cardgameacrrahul27.azurecr.io
          registryUsername: ${{ secrets.CARDGAMEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARDGAMEAPI_REGISTRY_PASSWORD }}
          containerAppName: card-game-api
          resourceGroup: Card-game-dev-rg
          imageToBuild: cardgameacrrahul27.azurecr.io/card-game-api:${{ github.sha }}


